apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysqldb
spec:
  selector: # mySQL Pod Should contain same labels
    matchLabels:
      app: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: mysqldb
    spec:
      containers:
        - image: mysql
          name: mysqldb
          env: # Setting Environmental Variables
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqldb-secret
                  key: password
            - name: MYSQL_DATABASE     # Setting Database Name from a 'ConfigMap'
              valueFrom:
                configMapKeyRef:
                  name: mysqldb-configmap
                  key: dbName
          ports:
            - containerPort: 3306
              name: mysqldb
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
# Define a 'Service' To Expose MySQL to Other Services
apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysqldb
  clusterIP: None # DNS is used, so clusterIP is not needed