# Will create a Persistent Volume Claim that will be used by the MySQL Pod to request for that provisioned storage.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim # Name of PVC essential for identifying the storage data
  labels:
    app: mysqldb
spec:
  storageClassName: standard-rwo
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 3Gi  # This will tell kubernetes about the amount of space we are trying to claim.
    limits:
      storage: 5Gi