spring:
  #set application name
  application:
    name: currency-exchange-service

  # for h2 database
  #h2:
  #  console:
  #    enabled: 'true'

  #database configuration
  datasource:
    #h2 database
    #url: jdbc:h2:mem:testdb

    # mysql database
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/currency_exchange_db?autoReconnect=true&useSSL=false
    username: root
    password: root

  # jpa configuration
  jpa:
    show-sql: "true"

    #h2 database
    #defer-datasource-initialization: 'true'

    #mysql database
    hibernate.ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

#enabled debug logging
logging:
  level:
    org:
      springframework: info

#running the application on port 8291
server:
  port: '8291'